# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iCoin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iCoin
  pod 'LightweightCharts', '~> 3.8.0'
end

target 'iCoin-WidgetExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iCoin-WidgetExtension

end
